# Generated by Django 2.2.24 on 2021-09-20 00:59

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('profile_picture', models.ImageField(blank=True, default='profile.png', null=True, upload_to='', verbose_name='Фото пользователя')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Пользователь-менеджер')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('contact', models.CharField(max_length=100, verbose_name='ФИО контактного лица')),
                ('sh_description', models.TextField(default='', verbose_name='Краткое описание компании')),
                ('description', models.TextField(verbose_name='Полное описание компании')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения записи')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес компании')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('ad_phone_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона 1')),
                ('ad_phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона 2')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Адрес электронной почты')),
                ('ad_email_1', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Дополнительный адрес электронной почты 1')),
                ('ad_email_2', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Дополнительный адрес электронной почты 2')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_create', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_update', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость проекта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_create', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_update', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без темы', max_length=100, verbose_name='Тема сообщения')),
                ('type_of_message', models.CharField(choices=[('Звонок', 'Звонок'), ('Переписка/Чат', 'Переписка/Чат'), ('Почта', 'Почта'), ('Заявка', 'Заявка'), ('Обратная связь', 'Обратная связь')], max_length=100, verbose_name='Канал обращения')),
                ('description', models.TextField(verbose_name='Описание сообщения')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания записи')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_create', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Project')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-date'],
            },
        ),
    ]
