# Generated by Django 2.2.24 on 2021-09-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210915_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
