# Generated by Django 2.2.24 on 2021-09-16 09:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210915_0924'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Пользователь-менеджер'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='', verbose_name='Фото пользователя'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('contact', models.CharField(max_length=100, verbose_name='ФИО контактного лица')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('date_of_create', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Дата последнего изменения записи')),
                ('address', models.TextField(verbose_name='Адрес компании')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Адрес электронной почты')),
                ('added_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['date_of_change'],
            },
        ),
    ]
