# Generated by Django 2.2.24 on 2021-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210916_1249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sh_description',
            field=models.TextField(default='', verbose_name='Краткое описание компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Полное описание компании'),
        ),
    ]
