# Generated by Django 2.2.24 on 2021-09-16 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210916_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ad_email_1',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Дополнительный адрес электронной почты 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='ad_email_2',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Дополнительный адрес электронной почты 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='ad_phone_1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='ad_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Дополнительный номер телефона 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='added_manager',
            field=models.ForeignKey(default='self.request.user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
