# Generated by Django 2.2.24 on 2021-09-16 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210916_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='added_manager',
            field=models.ForeignKey(default='request.user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись'),
        ),
    ]
