# Generated by Django 2.2.24 on 2021-09-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20210916_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='added_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='added_manager',
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись'),
        ),
    ]
