# Generated by Django 2.2.24 on 2021-09-16 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20210916_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_update', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_update', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_create', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, создавший запись'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_create', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
    ]
